### ISSUE TITLE
能不能增加一个getVisibleRect方法？

### ISSUE THREAD

**Issue by pzllla** [panpf/zoomimage#1]
之前使用了[SketchZoomImageView](https://github.com/panpf/sketch/blob/main/docs/wiki/zoom.md)，有调用这个方法。尝试了一下zoomimage，发现没有这个方法，不能直接切换，能不能考虑加上？

**Comment by panpf** [comment]
现在有的，你看下 sketchZoomImageView.zoomAbility. contentVisibleRect 属性

**Comment by panpf** [comment]
文档中都有可用属性的列举：https://github.com/panpf/zoomimage/blob/main/docs/wiki/getstarted.md#get-relevant-information%E8%8E%B7%E5%8F%96%E7%9B%B8%E5%85%B3%E4%BF%A1%E6%81%AF

**Comment by pzllla** [comment]
好的好的，谢谢大佬
