### ISSUE TITLE
请问未来会支持 item 图片过渡效果吗？

### ISSUE THREAD

**Issue by chachako** [panpf/zoomimage#10]
这个问题可能有点超出这个库的范畴，但是还是问一下（

zoomimage compose 之后会实现下面的效果吗？视频效果来自 https://github.com/Tencent/QMUI_Android/tree/master/photo/src/main/java/com/qmuiteam/photo/compose

zoomimage view 目前可以用 `ChangeImageTransfrom` 实现，但是 compose 我不清楚要如何实现 🥲 所以想问问大佬之后会不会内置（？）这种效果

https://github.com/panpf/zoomimage/assets/58068445/c6aeb389-c0fc-4bfb-b026-dafa37a070ff

**Comment by panpf** [comment]
不会在库里支持这种效果，因为这种效果实现起来很复杂需要前后两个页面互相配合，是无法在库层面搞定的

我帮你找了一个 compose 上的共享元素的库你可以看看 https://github.com/mxalbert1996/compose-shared-elements
