### ISSUE TITLE
不支持gif吗?

### ISSUE THREAD

**Issue by manitozhang** [panpf/zoomimage#13]

**Comment by panpf** [comment]
gif 跟 zoomimage 无关，属于图片加载框架的范畴

**Comment by manitozhang** [comment]
可以对gif做支持吗, 相当于对多种不同图片类型的支持

**Comment by panpf** [comment]
zoomimage 不区分图片类型，它是工作在 View 或 Compose 组件层面的，只要你将 gif 显示到 View 或 compose 组件上就可以，如果你不知道怎么将 gif 显示到 view 或 compose 上，可以去找找可以相应的加载图片的库
