### ISSUE TITLE
无法引入依赖库

### ISSUE THREAD

**Issue by manitozhang** [panpf/zoomimage#14]
**Describe the bug**

无法引入GlideView的依赖库

**Affected platforms**

Select of the platforms below:

- Android

**Affected components**
无法引入其他依赖库, 只能引入stecker的依赖库, 不知道是不是我项目和库的依赖,kotlin版本冲突还是编译器的问题
Select of the components below:

- ZoomImageView
- CoilZoomImageView
- GlideZoomImageView
- PicassoZoomImageView

**Versions**
- zoomimage version*: 1.0.1
- Kotlin version*: 1.6.21

**Running Devices**

Please accurately describe the device Model, OS version, and CPU Architecture

- XiaoMi Red mi note13; MIUI 14.0.6; arm64

**Sample code**

无

**Reproduction steps**

Please provide a detailed step-by-step guide on how to reproduce the issue you are experiencing.

**Expected behavior**

**Screenshots**

直接引入依赖库

**Additional context**

![image](https://github.com/panpf/zoomimage/assets/35214125/e0390c2a-dbe0-47a4-af93-327a215efd03)

**Comment by panpf** [comment]
出错了会在你的 build 日志中显示错误信息的，注意看

**Comment by manitozhang** [comment]
![Uploading image.png…]()

**Comment by manitozhang** [comment]
是因为aar的问题吗, 我依赖是否需要做额外的配置, 我引入sketch是正常的

![image](https://github.com/panpf/zoomimage/assets/35214125/9cbf9124-39ad-4feb-889f-79c6504cf363)

**Comment by manitozhang** [comment]
是因为我代理的原因吗, 我引入sketch是没问题的, 还是说我项目本身的gradle版本与库不一致, 我的gradle版本是8.0.1

![image](https://github.com/panpf/zoomimage/assets/35214125/f969c4ac-9216-4054-9820-f5cf188b9c2a)

**Comment by panpf** [comment]
aliyun 没有同步最新版本 的话就直接用 maven central

**Comment by manitozhang** [comment]
谢谢

**Comment by manitozhang** [comment]
`maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/apache-snapshots' }
        // 华为开源镜像：https://mirrors.huaweicloud.com
        maven { url 'https://repo.huaweicloud.com/repository/maven' }

        // JitPack 远程仓库：https://jitpack.io
        maven { url 'https://jitpack.io' }
        // MavenCentral 远程仓库：https://mvnrepository.com
        mavenCentral()
        google()
        jcenter()`

正常我在根目录的allprojects.repositories节点都有写, 正常应该在阿里云镜像找不到的话, 应该是去mavencenter找的,
而且在阿里云的镜像库是可以下载下来的, https://maven.aliyun.com/repository/public/io/github/panpf/zoomimage/zoomimage-view-glide/1.0.1/zoomimage-view-glide-1.0.1.aar

**Comment by panpf** [comment]
我发布包时只需要传到 maven central 就可以了，具体你要怎么下载用哪个镜像你可以自主选择，再者 gradle 仓库的规则我们也无法控制，建议你舍弃一切镜像

**Comment by manitozhang** [comment]
好的, 明白, 谢谢

**Comment by manitozhang** [comment]
我项目的compileSdkVersion是32, 无法引入啊

**Comment by manitozhang** [comment]
引入会不兼容

**Comment by panpf** [comment]
升级吧 铁子
