### ISSUE TITLE
佬，支持Java吗 ？ 有些老项目是用java写的，不打算换kt了

### ISSUE THREAD

**Issue by ffdsss** [panpf/zoomimage#15]
佬，支持Java吗 ？ 有些老项目是用java写的，不打算换kt了

**Comment by panpf** [comment]
Java 可以用，只是 API 会比较奇怪，凑合用吧

**Comment by ffdsss** [comment]
试了，java好像不行。 GlideZoomImageView和SketchZoomImageView加载url都会报错。

 Caused by: java.lang.NoSuchMethodError: No virtual method close()V in class Landroid/content/res/TypedArray; or its super classes (declaration of 'android.content.res.TypedArray' appears in /system/framework/framework.jar)

![image](https://github.com/panpf/zoomimage/assets/48895716/6e4f7140-efa0-40d1-afbc-2cc530ad5d66)


![image](https://github.com/panpf/zoomimage/assets/48895716/bf094bc4-e7b3-4694-a8ab-68adbe437c57)

示例图片：https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?ixid=M3w1NTU5ODJ8MHwxfHNlYXJjaHwxNnx8Y2F0fGVufDB8fHx8MTcwNjE3NTg4MXww&ixlib=rb-4.0.3

**Comment by panpf** [comment]
已发布修复此问题的 SNAPSHOT 版本 1.0.2-SNAPSHOT 到 SNAPSHOT 仓库，你先试试

**Comment by ffdsss** [comment]
> 已发布修复此问题的 SNAPSHOT 版本 1.0.2-SNAPSHOT 到 SNAPSHOT 仓库，你先试试

implementation 'io.github.panpf.zoomimage:zoomimage-view:1.0.2-SNAPSHOT'   是这个吗 ，没拉下来

**Comment by panpf** [comment]
在 SNAPSHOT 仓库

**Comment by panpf** [comment]
怎么了，能继续用了吗？

**Comment by ffdsss** [comment]
> 怎么样了，能继续用了吗？

没找到仓库，可以发一下id吗

**Comment by panpf** [comment]
添加一下这个仓库 https://s01.oss.sonatype.org/content/repositories/snapshots/

**Comment by panpf** [comment]
此问题已在 1.0.2 版本修复，请更新到新版本
