### ISSUE TITLE
使用GlideZoomImageView读取不到contentOriginSize,导致大图像显示模糊

### ISSUE THREAD

**Issue by lepecoder** [panpf/zoomimage#16]
**Describe the bug**

使用GlideZoomImageView读取不到contentOriginSize,导致大图像显示模糊

**Affected platforms**

- Android

**Affected components**

Select of the components below:

- GlideAsyncZoomImage
- GlideZoomImageView

**Versions**

最新demo

**Running Devices**

Please accurately describe the device Model, OS version, and CPU Architecture

- redMi K30 Pro

**Sample code**

If possible, provide a small piece of code that reproduces the problem. If the code snippet is too
large to paste here, please link to a Gist, a GitHub repo, or any other public code repository.

**Reproduction steps**

Please provide a detailed step-by-step guide on how to reproduce the issue you are experiencing.

**Expected behavior**

**Screenshots**

![20240204-113023](https://github.com/panpf/zoomimage/assets/34852544/554c9ae5-a5b2-430f-adbe-af8b28919e91)
![20240204-113015](https://github.com/panpf/zoomimage/assets/34852544/0fbbcffe-1195-4b71-b8f4-95e696f0aa73)

**Additional context**

**Comment by panpf** [comment]
此问题已在 1.0.2 版本修复，请更新到新版本
