### ISSUE TITLE
使用CoilZoomImageView 加载图片时候会抛出异常 不过不影响使用 缩放等都正常

### ISSUE THREAD

**Issue by NeVaDaAAA** [panpf/zoomimage#17]
**Describe the bug**

![image](https://github.com/panpf/zoomimage/assets/20659340/3a5bbaf9-982e-461a-9a45-cf4d7275312c)

**Affected platforms**

Select of the platforms below:

- Android

**Affected components**

Select of the components below:

- CoilZoomImageView

**Versions**
- zoomimage version*:1.0.2
- Kotlin version*:1.9.0
- JDK version(Only Desktop): 11

**Running Devices**

Please accurately describe the device Model, OS version, and CPU Architecture

- Lenovo TB-8505N Android 10

**Sample code**

![image](https://github.com/panpf/zoomimage/assets/20659340/4764b499-f21b-4dbb-9fff-b31e13ccad8c)

**Comment by panpf** [comment]
coil 的 data 要将 http 链接转成 android uri 如下：
```
load(Uri.parse(imageData)) {
// ...
}
```

**Comment by NeVaDaAAA** [comment]
感谢作者 现在没有异常了

**Comment by XDao7** [comment]
补充一点，这个问题对于小图加载不会产生影响，但是会导致大图子采样失效，昨天刚遇到了。
