### ISSUE TITLE
双指捏合缩放的小问题

### ISSUE THREAD

**Issue by hdinson** [panpf/zoomimage#18]
现象描述
1/当图片两指持续缩小时，两指到达一定的距离后，将不再继续缩小
2/当图片两指放大时，开始两指距离很近，图片不放大，后持续加大两指距离，需要到一定的距离后才能触发图片放大

双指捏和缩放的最小触发距离能不能提供 api 进行设置？

**Comment by hdinson** [comment]
另:
sketchZoomImageView.displayImage()  能新增 Bitmap 和 ByteArray 类型

**Comment by panpf** [comment]
> 现象描述 1/当图片两指持续缩小时，两指到达一定的距离后，将不再继续缩小 2/当图片两指放大时，开始两指距离很近，图片不放大，后持续加大两指距离，需要到一定的距离后才能触发图片放大
> 
> 双指捏和缩放的最小触发距离能不能提供 api 进行设置？

双指缩放并没有使用自定义的算法，是用的系统默认的算法。我认为这部分还是和系统保持一致比较好。

**Comment by panpf** [comment]
> 另: sketchZoomImageView.displayImage() 能新增 Bitmap 和 ByteArray 类型

直接使用 Bitmap 和 ByteArray 想必只有在极个别的场景下才有此需求，这种场景下可以直接使用基础的 ZoomImageView，不要使用集成了图片加载器的

**Comment by Mett-Barr** [comment]
> 另: sketchZoomImageView.displayImage() 能新增 Bitmap 和 ByteArray 类型

不確定場景和我一不一樣，你的數據源是 File 資源
我的是 File -> InputStream -> fun loadImageBitmap(inputStream: InputStream): ImageBitmap
到最後轉成 ImageBitmap 就能顯示了

**Comment by panpf** [comment]
@hdinson 你试试现在的最新版本看还有没有问题
