### ISSUE TITLE
加载大图报错了，麻烦大佬看一下

### ISSUE THREAD

**Issue by pzllla** [panpf/zoomimage#2]
尝试用zoomImage加载大图，直接报错了，不知道是不是使用方式有问题，麻烦大佬看一下
demo：
[TestZoomImage.zip](https://github.com/panpf/zoomimage/files/12520492/TestZoomImage.zip)

报错：
<img width="1671" alt="image" src="https://github.com/panpf/zoomimage/assets/131447030/e03f26f0-31f9-4ef8-862d-ae390dfb8c7c">

**Comment by panpf** [comment]
异常里已经说的很明白了，coil 加载了一个超过绘制限制的 Bitmap，导致无法绘制

你把 precision(coil.size.Precision.INEXACT) 去掉就可以了，你为什么要设置这个？

再遇到此类问题先把所有额外的设置全部去掉，再看看有没有问题，没问题的话就一个个把额外的设置加回来，就知道哪里出问题了

**Comment by panpf** [comment]
再者 imageview 需要有明确的宽高，你在 RecyclerView 中使用，你设置高度 Match_parent，那么 imageView 的高会是多少呢？

**Comment by panpf** [comment]
我理解你是想用 zoomimage + RecyclerView 实现漫画的需求？如果是这样的话，我是觉得 zoomimage 并不适合，并且很难达到理想中漫画的需求，你需要自己在参考 zoomimage 的基础上开发专门用于漫画的组件

**Comment by pzllla** [comment]
> 异常里已经说的很明白了，coil 加载了一个超过绘制限制的 Bitmap，导致无法绘制
> 
> 你把 precision(coil.size.Precision.INEXACT) 去掉就可以了，你为什么要设置这个？
> 
> 再遇到此类问题先把所有额外的设置全部去掉，再看看有没有问题，没问题的话就一个个把额外的设置加回来，就知道哪里出问题了

<img width="761" alt="image" src="https://github.com/panpf/zoomimage/assets/131447030/a42dbe86-c6fe-45d7-a8b2-2dcb6c812b0c">
只是照抄了example的设置，以为不用设置宽高就能查看大图，我印象中SketchZoomImage不用设置宽高也能查看大图？

**Comment by panpf** [comment]
我是在 ViewPagaer 中使用，你是在 RecyclerView 中，根本不一样的，RecyclerView 的 item 的高度是没有固定值的

**Comment by pzllla** [comment]
> 不是需要设置宽高，是你在 RecyclerView 中 item 的高是 match_parent 时，这个高度就是未知的，coil 可能遇到未知的高度就不再限制图片大小了

还有这种问题，ViewPagaer2里面使用的就是RecyclerView，看来也会有问题，我试试ViewPagaer。

**Comment by pzllla** [comment]
> 不是需要设置宽高，是你在 RecyclerView 中 item 的高是 match_parent 时，这个高度就是未知的，coil 可能遇到未知的高度就不再限制图片大小了

那是不是只有coil有这个问题，还是说其他图片加载库和RecyclerView一起，就不会出现这个现象？

**Comment by panpf** [comment]
> > 不是需要设置宽高，是你在 RecyclerView 中 item 的高是 match_parent 时，这个高度就是未知的，coil 可能遇到未知的高度就不再限制图片大小了
> 
> 还有这种问题，ViewPagaer2里面使用的就是RecyclerView，看来也会有问题，我试试ViewPagaer。

ViewPager 不会有问题，因为它在测量 item 的时候会给个最大高度，RecyclerView 则不会

**Comment by panpf** [comment]
> > 不是需要设置宽高，是你在 RecyclerView 中 item 的高是 match_parent 时，这个高度就是未知的，coil 可能遇到未知的高度就不再限制图片大小了
> 
> 那是不是只有coil有这个问题，还是说其他图片加载库和RecyclerView一起，就不会出现这个现象？

你可以测试一下，总之就是你的使用场景和配置导致图片加载框架加载了一个超出绘制限制的 bitmap，具体不同的图片加载框架是怎么处理此问题的，你可以自己测试一番加深理解

**Comment by pzllla** [comment]
okok
