### ISSUE TITLE
希望添加对于Bitmap的支持（Support Bitmap for XXXZoomImageView）

### ISSUE THREAD

**Issue by savet-save** [panpf/zoomimage#20]
如果使用bitmap数据载入GlideZoomImageView中，会有以下提示
if use bitmap into GlideZoomImageView，has following tips
```
GlideZoomImageView. Can't use Subsampling, unsupported model: 'android.graphics.Bitmap@1e22c0'
```

example：
```kotlin
    private fun showImage(image: Bitmap) {
        binding.detectImageView.visibility = View.VISIBLE
        Glide.with(this@GalleryFragment)
            .load(image)
            .into(binding.detectImageView)
   }
```

如果使用SketchZoomImageView 则无法直接使用bitmap数据（需要转换）。
If you use SketchZoomImageView, you cannot use bitmap data directly (conversion is required).
所以希望作者添加对于Bitmap的支持，或者给个修改方法，谢谢！
So I hope the author adds support for Bitmap, or give a modification method, thank you!

**Comment by panpf** [comment]
xxxZoomImageView 系列的类是更多是为了异步加载来自非内存的图片，如网络、本地。
既然你已经拿到 bitmap 了就直接使用基础的 ZoomImageView 即可。

另外直接对 Bitmap 缩放查看，想来也是仅限于个别场景，如图像裁剪编辑，这时候更应该基于基础的 ZoomImageView 去定制
