### ISSUE TITLE
能否支持一下拖放退出的效果

### ISSUE THREAD

**Issue by yxiangTang** [panpf/zoomimage#23]
佬，能否集成一下类似微信那种拖放退出图片预览的效果，感觉这个需求也比较常见

**Comment by panpf** [comment]
这个功能不属于 zoomimage 的范畴。你可以找一个现成的效果案例，将 ImageView 替换成 ZoomImageView，在此过程中还需要 ZoomImageView 提供什么支持来实现这个效果，可以告诉我
