### ISSUE TITLE
关于缩放限制的问题

### ISSUE THREAD

**Issue by yvone1991** [panpf/zoomimage#24]
compose版本：
1、minscale好像无法自定义数值，比如产品要求在最小在20%，但是我无法限制他
```
data class MyScalesCalculator(
    val customMinScale: Float,
    val customMediumScale: Float = 3f,
    val customMaxScale: Float
) : ScalesCalculator {

    override fun calculate(
        containerSize: IntSizeCompat,
        contentSize: IntSizeCompat,
        contentOriginSize: IntSizeCompat,
        contentScale: ContentScaleCompat,
        minScale: Float,
        initialScale: Float
    ): ScalesCalculator.Result {
        return ScalesCalculator.Result(
            minScale = customMinScale,
            mediumScale = customMediumScale,
            maxScale = customMaxScale
        )
    }

    override fun toString(): String {
        return "CustomScalesCalculator(" +
                "customMinScale=${customMinScale}, " +
                "customMediumScale=${customMediumScale}, " +
                "customMaxScale=${customMaxScale})"
    }
}

2、关于触摸事件，好像无法捕获到up和cancel事件，能否开放down和up事件。一些需求场景是需要操作的时候隐藏一些ui，然后抬起后过几秒显示一些ui。
我尝试用pointinput无法拦截，使用pointerInteropFilter也只能获取down事件

**Comment by panpf** [comment]
1. minScale 是根据缩略图大小、容器大小、ContentScale 计算出来的，它不是一个固定的值。我需要你明确描述你的需求场景，看需求是否合理以及是否有其它方式可以满足
2. 直接在 ZoomImage 上开放此接口好像不太合适，我的考虑是这不是常见的需求。你不要直接在 ZoomImage 上拦截触摸事件，你可以用一个 Box 将 ZoomImage 包一层，然后在 Box 上去拦截触摸事件

**Comment by yvone1991** [comment]
> 1. minScale 是根据缩略图大小、容器大小、ContentScale 计算出来的，它不是一个固定的值。我需要你明确描述你的需求场景，看需求是否合理以及是否有其它方式可以满足
> 2. 直接在 ZoomImage 上开放此接口好像不太合适，我的考虑是这不是常见的需求。你不要直接在 ZoomImage 上拦截触摸事件，你可以用一个 Box 将 ZoomImage 包一层，然后在 Box 上去拦截触摸事件

1、是的，我们的产品比较坑爹，要求可以缩小到20%……因为我们做几百寸的12k大屏安卓，是需要支持缩放的，这样可以满足用户在哪里操作的就在那里显示的场景（应用内自由位置，图片太大了不能缩小用户够不到）
2、尝试了包一层，或者再盖一层box，但是指针时间被你消费了，我拿不到。

我现在的做法是把你的源码下下来改，不过感觉不够优雅，时间投入成本也比较大。。毕竟我电脑没有跨平台环境，昨天搞环境花了比较久的时间……

不过如果可能的话，能开放minscale和触控分发我觉得是蛮有必要的。。。而且我现在新增了crop截屏模式，兼容性也不是特别高，我正在想办法如何获取到不同contentscale模式下的rect区域，从而限制我的crop矩形

**Comment by panpf** [comment]
问题 1：看了你的描述大概有了一个框架，在一个常规图片缩放查看器的基础上你还需要以下功能：
1. 因为屏幕非常大所以需要缩小到很小，然后还能在容器内自由移动位置
2. 你还要叠加批注图层支持用户的手写或者绘画
3. 你还要叠加裁剪图层并获取需要裁剪的位置

如果我的理解没错的话，我觉得你需要基于 zoomimag 的源码去自定义适合你这个场景的组件了，因为我初步思考下来还需要做很大的改动才能满足你的需求。你只需拷贝 common 和 android 部分的源码即可

问题 2：这个问题倒是好改，加一个 InteractionSource 参数即可，但是目前我的重心还是在我的其它项目上，可能还得个把月才能到这儿

**Comment by yvone1991** [comment]
> 问题 1：看了你的描述大概有了一个框架，在一个常规图片缩放查看器的基础上你还需要以下功能：
> 
> 1. 因为屏幕非常大所以需要缩小到很小，然后还能在容器内自由移动位置
> 2. 你还要叠加批注图层支持用户的手写或者绘画
> 3. 你还要叠加裁剪图层并获取需要裁剪的位置
> 
> 如果我的理解没错的话，我觉得你需要基于 zoomimag 的源码去自定义适合你这个场景的组件了，因为我初步思考下来还需要做很大的改动才能满足你的需求。你只需拷贝 common 和 android 部分的源码即可
> 
> 问题 2：这个问题倒是好改，加一个 InteractionSource 参数即可，但是目前我的重心还是在我的其它项目上，可能还得个把月才能到这儿

1、差不多，其实我就缺个缩小的限制了，这个月跑通源码过来了解一下吧。。。批注和裁剪已经实现，我只需要实现缩小+缩小后移动即可。
2、你说的InteractionSource这个我倒是没想到，我去了解一下。。我的印象中InteractionSource被我拿来做点击特效了。。。可能刚学compose不久。

**Comment by yvone1991** [comment]
> 问题 1：看了你的描述大概有了一个框架，在一个常规图片缩放查看器的基础上你还需要以下功能：
> 
> 1. 因为屏幕非常大所以需要缩小到很小，然后还能在容器内自由移动位置
> 2. 你还要叠加批注图层支持用户的手写或者绘画
> 3. 你还要叠加裁剪图层并获取需要裁剪的位置
> 
> 如果我的理解没错的话，我觉得你需要基于 zoomimag 的源码去自定义适合你这个场景的组件了，因为我初步思考下来还需要做很大的改动才能满足你的需求。你只需拷贝 common 和 android 部分的源码即可
> 
> 问题 2：这个问题倒是好改，加一个 InteractionSource 参数即可，但是目前我的重心还是在我的其它项目上，可能还得个把月才能到这儿

```
sealed class PressInteraction : Interaction {
    data object Pressed : PressInteraction()
    data object Released : PressInteraction()
}

@Composable
fun Modifier.detectPointerInteractions(
    interactionSource: MutableInteractionSource,
    coroutineScope: CoroutineScope,
): Modifier = pointerInput(interactionSource) {
    coroutineScope.launch {
        awaitPointerEventScope {
            var isPointerPressed = false
            while (true) {
                val event = awaitPointerEvent()
                handlePointerEvent(event, isPointerPressed, interactionSource).also {
                    isPointerPressed = it
                }
            }
        }
    }
}

private fun handlePointerEvent(
    event: PointerEvent,
    isPointerPressed: Boolean,
    interactionSource: MutableInteractionSource,
): Boolean {
    val anyPointerPressed = event.changes.any { it.pressed }
    if (anyPointerPressed && !isPointerPressed) {
        interactionSource.tryEmit(PressInteraction.Pressed)
        return true
    } else if (!anyPointerPressed && isPointerPressed) {
        interactionSource.tryEmit(PressInteraction.Released)
        return false
    }
    return isPointerPressed
}
```

通过InteractionSource搞定了，不会被你的事件消费，问题2-OK
