### ISSUE TITLE
GlideZoomImageViewFragment 封面图片放大 之后，能拿到放大之后的MATRIX 吗 ，这边需求就是，封面图放大之后，播放视频和封面图一样大，在同一个位置

### ISSUE THREAD

**Issue by LCliuchun** [panpf/zoomimage#26]

**Comment by panpf** [comment]
https://github.com/panpf/zoomimage/blob/main/docs/wiki/scale_zh.md#%E5%8F%AF%E8%AE%BF%E9%97%AE%E5%B1%9E%E6%80%A7

**Comment by LCliuchun** [comment]
这边能将图片放大的得matrix 回调出来吗，这边需要知道这个matrix 是在哪一个点放大的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "panpf/zoomimage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月17日(星期一) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [panpf/zoomimage] GlideZoomImageViewFragment 封面图片放大 之后，能拿到放大之后的MATRIX 吗 ，这边需求就是，封面图放大之后，播放视频和封面图一样大，在同一个位置 (Issue #26)





 
https://github.com/panpf/zoomimage/blob/main/docs/wiki/scale_zh.md#%E5%8F%AF%E8%AE%BF%E9%97%AE%E5%B1%9E%E6%80%A7

**Comment by panpf** [comment]
请重新组织并且详细说明你的问题

**Comment by LCliuchun** [comment]
封面图片放大 之后，能拿到放大之后的MATRIX 吗
需求就是，图片在一个位置放大之后，后面的是否也在这个点放大，所以需要拿到图片放大的MATRIX

**Comment by panpf** [comment]
https://github.com/panpf/zoomimage/blob/8e5debefa937b7b7290fd4680182de6341a76656/zoomimage-view/src/main/kotlin/com/github/panpf/zoomimage/ZoomImageView.kt#L168

照着抄就行了

**Comment by LCliuchun** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "panpf/zoomimage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 下午2:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [panpf/zoomimage] GlideZoomImageViewFragment 封面图片放大 之后，能拿到放大之后的MATRIX 吗 ，这边需求就是，封面图放大之后，播放视频和封面图一样大，在同一个位置 (Issue #26)





 
https://github.com/panpf/zoomimage/blob/8e5debefa937b7b7290fd4680182de6341a76656/zoomimage-view/src/main/kotlin/com/github/panpf/zoomimage/ZoomImageView.kt#L169
 
照着抄就行了
