### ISSUE TITLE
Glide Compose 版本兼容问题

### ISSUE THREAD

**Issue by leavesCZY** [panpf/zoomimage#3]
大佬真的高效，这么快就修复问题了。另外还有个关于 Glide 的问题想反馈下。现在 zoomimage 中使用的 glide-ktx 是 1.0.0-alpha.3 版本，而最新版本（1.0.0-alpha.6）的 glide-compose 关联的是 1.0.0-alpha.5 版本的 glide-ktx ，高版本的 AsyncGlideSize 类不包含构造函数，而由于 zoomimage 中还是会通过有参构造函数来实例化 AsyncGlideSize，所以如果引用方使用的是最新版本的 glide-compose 的话，就会在运行时由于 GlideZoomAsyncImage 而崩溃了

**Comment by panpf** [comment]
这个问题由于 glide compose 和它以来的KTX 还是 alpha 版本，所以 API 变动是在预期之内的，等它稳定了到 beta 版本了应该就不会有这个问题。

我也一直在等它的 beta版本等了一个月了，估计还得一段时间。

**Comment by leavesCZY** [comment]
是的，这种 API 变动在 alpha 阶段也属正常，提个 issue 方便后边有人遇到相同情况时好定位问题

**Comment by panpf** [comment]
没毛病 👍🏻
