### ISSUE TITLE
Support for zooming based on mouse pointer & scroll wheel for desktop platforms

### ISSUE THREAD

**Issue by starry-shivam** [panpf/zoomimage#35]
Currently, zooming only happens when double-clicking on a specific section of the image. It would be great if zooming via mouse pointer + scroll wheel was also supported (like in the Windows Photos app). As far as I know, the only way to do it right now is by calling `ZoomState.scale(...)`, somehow detecting the scroll event & values and pointer position for the focal point. However, I don't yet know the bounds of this method or how to implement it properly by myself.

**Comment by panpf** [comment]
Will consider it, please look forward to it

**Comment by panpf** [comment]
@starry-shivam According to the function of the mouse rolling wheel and pointer position, it has been submitted to the DEV branch. Welcome to download the code of the DEV branch and run the desktop version of SAMPLE to experience it, and then feedback me your feelings and suggestions

**Comment by starry-shivam** [comment]
Wow thanks! I'll give it a try

**Comment by panpf** [comment]
> Wow thanks! I'll give it a try

Hi, have you tried it? How was your experience?

**Comment by starry-shivam** [comment]
> Hi, have you tried it? How was your experience?

Yes, I've tried the desktop sample in dev branch, it seems work as i expected :)

**Comment by panpf** [comment]
Available in v1.1.0-alpha06

**Comment by jpage4500** [comment]
@panpf - I'm not sure if this is the same feature I'm looking for or not.. I was hoping to get desktop support for pinch to zoom on a trackpad. I think it's similar to the mouse wheel technically but not sure.

Anyway, is the logic in the released version of this library today?

thanks,
Joe

**Comment by jpage4500** [comment]
just going to answer my own question.. yes, mouse wheel support IS in the release version. But, it's different than trackpad pinch to zoom support - or at least it must be because that doesn't work for me (Macbook)

**Comment by panpf** [comment]
Trackpad zoom is not supported yet, you can try to implement this feature based on the scale api
