### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by andiosdev** [panpf/zoomimage#38]
**Describe the bug**
Followed the instruction and yet image is not loading

**Affected platforms**
- Android
- iOS

**Affected components**
- SketchAsyncZoomImage
- CoilAsyncZoomImage

**Sample code**
SketchZoomAsyncImage(
    uri = "http://sample.com/huge_world.jpeg",
    contentDescription = "view image",
    modifier = Modifier.fillMaxSize(),
)

CoilZoomAsyncImage(
    model = "http://sample.com/huge_world.jpeg",
    contentDescription = "view image",
    modifier = Modifier.fillMaxSize(),
)

**Comment by panpf** [comment]
Please post your actual code and error log.

**Comment by andiosdev** [comment]
I don't think it has error, image just does not load. I used the actual code mentioned and followed the instruction. I'm not sure if I'm missing something.

**Comment by panpf** [comment]
I want to know from your actual code the url of the image you actually loaded. If it is "http://sample.com/huge_world.jpeg" then there must be something wrong because it is a fake url and it cannot be accessed. I just use it for a demonstration.

**Comment by andiosdev** [comment]
This is the image url I used:
https://cdn.pixabay.com/photo/2016/09/07/10/37/kermit-1651325_1280.jpg
