### ISSUE TITLE
怎么单独引用库，现在引用之后完全报错

### ISSUE THREAD

**Issue by everyline** [panpf/zoomimage#39]
**Describe the problem**

Explain the performance issue you're experiencing, including the following details:

- What specific issue did you encounter? (e.g. missing frames, high CPU usage, memory leaks)
- Have you noticed any patterns or specific circumstances under which the problem occurs?

**Affected platforms**

Select of the platforms below:

- Android
- Desktop

**Affected components**

Select of the components below:

- ZoomImage
- SketchAsyncZoomImage
- CoilAsyncZoomImage
- GlideAsyncZoomImage
- ZoomImageView
- SketchZoomImageView
- CoilZoomImageView
- GlideZoomImageView
- PicassoZoomImageView

**Versions**

- zoomimage version*:
- Kotlin version:
- Compose version(s)* (Jetpack/Multiplatform):
- JDK version(Only Desktop):

**Running Devices**

Please accurately describe the device Model, OS version, and CPU Architecture

- MacBookPro 14 2021; macOS 13.4.1; arm64
- XiaoMi MIX 4; MIUI 14.0.6; arm64

**Sample code**

If possible, provide a small piece of code that reproduces the problem. If the code snippet is too
large to paste here, please link to a Gist, a GitHub repo, or any other public code repository.

**Reproduction steps**

Please provide a detailed step-by-step guide on how to reproduce the issue you are experiencing.

**Video**

If you're reporting slow app work or missing frames, please provide a video of the problem.

**Profiling data**

Please provide any relevant profiling data that might be helpful. This could include information
like FPS, memory usage, CPU time, or any other data that could provide insight into the performance
issue.

**Additional information**

Provide any other details that you think might be helpful for us to understand the problem. This
could include things like the system configuration, external factors, etc.

**Comment by panpf** [comment]
1. 你是要解决报错问题还是要单独引用？
2. 报错问题，报什么错？请提供截图或报错信息。
3. 单独引用是什么意思？现在每个模块都是可以单独使用的，你还要怎么个单独引用法？

**Comment by everyline** [comment]
![QQ_1722907098967](https://github.com/user-attachments/assets/3e8ce916-b1e9-4ad9-a98c-5900b09739ea)

**Comment by panpf** [comment]
I don't see any ZoomImage related errors in your screenshots.

**Comment by everyline** [comment]
我升级了gradle就可以了 谢谢大佬
