### ISSUE TITLE
请问可以支持一下低版本的kotlin么？

### ISSUE THREAD

**Issue by XDao7** [panpf/zoomimage#4]
The binary version of its metadata is 1.9.0, expected version is 1.7.1.
在我项目当中编译会提示如上报错，我目前的org.jetbrains.kotlin.android是1.7.20，kotlin版本好像跟compose是绑在一起的，升不上去啊。

**Comment by panpf** [comment]
我自己的还好办一些，主要是 glide compose 用了 1.5.0 版本了， 所以导致很难往下降，实在不行，你自己拿源码编译个低版本的

**Comment by panpf** [comment]
能升上来就好，反正早晚是要升的

**Comment by manitozhang** [comment]
@XDao7 大佬, 可以开源发一份吗?

**Comment by XDao7** [comment]
> @XDao7 大佬, 可以开源发一份吗?

什么开源的？你是说低版本kotlin的？我没有弄，我把工程的kotlin版本升上去了。
