### ISSUE TITLE
Image not aligned after orientation change

### ISSUE THREAD

**Issue by IacobIonut01** [panpf/zoomimage#41]
**Describe the bug**

The Image is not longer aligned to Center (for example) after an orientation change (rotate the phone) - however, it returns to the default Top-Start. After re-opening the page on the new orientation, the image loads fine, however, if it rotates again, moves back to the Top-Start alignment

**Affected platforms**

- Android

**Affected components**

Select of the components below:

- SketchAsyncZoomImage

**Versions**

- zoomimage version*: 1.1.0-alpha05
- Kotlin version*: 2.0.0
- Compose version(s)* (Jetpack): 2024.06.00

**Running Devices**

- Pixel 6; Android 15; arm64
- Pixel 7; Android 14; arm64

**Sample code**

```kotlin
    Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
        SketchZoomAsyncImage(
            modifier = Modifier.fillMaxSize(),
            uri = media.uri.toString(),
            contentScale = ContentScale.Fit,
            contentDescription = null
        )
    }
```

**Reproduction steps**

- Create Compose Screen with given snippet
- Set an uri
- Open the app and observe the image being correctly displayed
- Rotate the phone screen to landscase
- Observe the image being aligned to the Top-Start instead
- Rotate again to portrait and observe the image staying to Top-Start

**Expected behavior**

- Create Compose Screen with given snippet
- Set an uri
- Open the app and observe the image being correctly displayed
- Rotate the phone screen to landscase
- Observe the image being correctly displayed
- Rotate again to portrait and observe the image being correctly displayed

**Screenshots**

![Screenshot_20240813_221546](https://github.com/user-attachments/assets/230e2a1e-b666-4c1d-8bed-011b63681fba)
![Screenshot_20240813_221559](https://github.com/user-attachments/assets/eeae36ec-f4a0-4648-b162-576918b8ceff)
![Screenshot_20240813_221610](https://github.com/user-attachments/assets/97a71b0f-8a56-4df4-98ec-3516922fa293)

**Additional context**

None.

Thanks for creating this library, completely full-fills my use-cases, but there's this small thing that delays me to release the version with your library instead of coil and telephoto

**Comment by IacobIonut01** [comment]
I think it defaults to this on orientation change, maybe the state is not held correctly trough configuration changes
https://github.com/panpf/zoomimage/blob/main/zoomimage-compose-sketch-core/src/commonMain/kotlin/com/github/panpf/zoomimage/SketchZoomAsyncImage.kt#L296

**Comment by panpf** [comment]
```kotlin
SketchZoomAsyncImage(
      modifier = Modifier.fillMaxSize(),
      uri = media.uri.toString(),
      contentScale = ContentScale.Fit,
      alignment = Alignemnt.Center,
      contentDescription = null
)
```

You can get rid of the Box and set the alignment directly using the alignment parameter of SketchZoomAsyncImage

**Comment by IacobIonut01** [comment]
I need the box to overlay the blur and the normal image.

**Comment by panpf** [comment]
Ok, let me look into the issue again. My plan is to release a new version this Friday which should fix this issue.

**Comment by IacobIonut01** [comment]
Thanks! I'm looking forward to it

**Comment by panpf** [comment]
I have tried many times and still can't reproduce this problem. Can you create a simple complete project that can repeat this problem for me? 

Here is my demonstration video

https://github.com/user-attachments/assets/d8dd7caa-ff41-4d20-9524-1c158536e9ec

**Comment by IacobIonut01** [comment]
> I have tried many times and still can't reproduce this problem. Can you create a simple complete project that can repeat this problem for me?
> 
> Here is my demonstration video
> 
>  2024-08-14.23.18.57.mp4

I'll double check my project then I'll get back with a sample project

**Comment by IacobIonut01** [comment]
Can you try in the context of an Horizontal Pager?

**Comment by IacobIonut01** [comment]
This reproduces the issue (while this is an extreme measure - having the key to constantly recompose the screen - something for sure it's wrong in my project if this happens)

```koltin
val key = Random.nextInt()
key(key) {
    SketchZoomAsyncImage(
        modifier = Modifier.fillMaxSize(),
        uri = "content://media/external/images/media/54",
        contentDescription = null
    )
}
```

**Comment by IacobIonut01** [comment]
@panpf I have solved the issue!

The culprit: (AndroidManifest.xml)
android:configChanges="orientation"

**Comment by panpf** [comment]
> This reproduces the issue (while this is an extreme measure - having the key to constantly recompose the screen - something for sure it's wrong in my project if this happens)
> 
> ```
> val key = Random.nextInt()
> key(key) {
>     SketchZoomAsyncImage(
>         modifier = Modifier.fillMaxSize(),
>         uri = "content://media/external/images/media/54",
>         contentDescription = null
>     )
> }
> ```



You are doing this wrong, please remove the random key, it will cause the SketchZoomAsyncImage component to load/destroy in a loop and never stop. You can either not set the key or use uri as the key.

You can see the image because there is a memory cache. After the second time, it is loaded from the memory cache, which will be very fast.

The default alignment of the image is TopStart. SketchZoomAsyncImage will calculate the offset based on the actual Alignment after the image is loaded successfully. Unfortunately, the SketchZoomAsyncImage component is destroyed before it can calculate the offset. This cycle repeats and results in the result you see now.

**Comment by panpf** [comment]
> @panpf I have solved the issue!
> 
> The culprit: (AndroidManifest.xml) android:configChanges="orientation"

I have tested this and it does not cause this problem.

**Comment by IacobIonut01** [comment]
> > @panpf I have solved the issue!
> > The culprit: (AndroidManifest.xml) android:configChanges="orientation"
> 
> I have tested this and it does not cause this problem.

"keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"

Have you tried with the full set?

**Comment by IacobIonut01** [comment]
> > This reproduces the issue (while this is an extreme measure - having the key to constantly recompose the screen - something for sure it's wrong in my project if this happens)
> > ```
> > val key = Random.nextInt()
> > key(key) {
> >     SketchZoomAsyncImage(
> >         modifier = Modifier.fillMaxSize(),
> >         uri = "content://media/external/images/media/54",
> >         contentDescription = null
> >     )
> > }
> > ```
> 
> You are doing this wrong, please remove the random key, it will cause the SketchZoomAsyncImage component to load/destroy in a loop and never stop. You can either not set the key or use uri as the key.
> 
> You can see the image because there is a memory cache. After the second time, it is loaded from the memory cache, which will be very fast.
> 
> The default alignment of the image is TopStart. SketchZoomAsyncImage will calculate the offset based on the actual Alignment after the image is loaded successfully. Unfortunately, the SketchZoomAsyncImage component is destroyed before it can calculate the offset. This cycle repeats and results in the result you see now.

Yeah I know, it was purely experimental.

**Comment by panpf** [comment]
I only tried orientation

**Comment by IacobIonut01** [comment]
> > > @panpf I have solved the issue!
> > > The culprit: (AndroidManifest.xml) android:configChanges="orientation"
> > 
> > 
> > I have tested this and it does not cause this problem.
> 
> "keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
> 
> Have you tried with the full set?

Because removing the orientation flag from there it fixed the bug on my side

**Comment by panpf** [comment]
This is my example, I can't reproduce the problem

```xml
<application
        android:name="com.github.panpf.zoomimage.sample.MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:networkSecurityConfig="@xml/network_security_config"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name="com.github.panpf.zoomimage.sample.MainActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
    </application>
```

```kotlin
class MainActivity : BaseActivity() {

    @OptIn(ExperimentalFoundationApi::class)
    @SuppressLint("RestrictedApi")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        EdgeToEdgeUtils.applyEdgeToEdge(/* window = */ window,/* edgeToEdgeEnabled = */ true)
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
            window.statusBarColor = Color.parseColor("#60000000")
        }
        if (Build.VERSION.SDK_INT == Build.VERSION_CODES.O) {
            window.navigationBarColor = Color.TRANSPARENT
        }

        setContent {
            HorizontalPager(
                state = rememberPagerState {
                    ResourceImages.values.size
                },
                modifier = Modifier.fillMaxSize()
            ) {
                SketchZoomAsyncImage(
                    uri = ResourceImages.values[it].uri,
                    contentDescription = "",
                    modifier = Modifier.fillMaxSize()
                )
            }
        }
    }
}
```

**Comment by panpf** [comment]
@IacobIonut01 Is there any new progress?

**Comment by IacobIonut01** [comment]
I'll close the issue as I have not managed to isolate the issue using a sample project, just in my case it seems that only the orientation flag was causing issue in this specific case, If I manage to properly reproduce the issue with a clean sample app, I'll re-open it. Until then, thanks for helping me out with this amazing library

**Comment by panpf** [comment]
Thank you for your appreciation. If this library really helps you, I hope you can recommend it to others who need an image zoom library, because the more people use it, the better it will become.

**Comment by IacobIonut01** [comment]
For sure!
