### ISSUE TITLE
使用GlideZoomImageView 加载部分gif会无法播放

### ISSUE THREAD

**Issue by yxiangTang** [panpf/zoomimage#43]
**Describe the bug**

使用GlideZoomImageView 加载部分gif会无法播放。

**Affected platforms**

Select of the platforms below:

- Android

**Affected components**

Select of the components below:

- GlideAsyncZoomImage

**Versions**

- zoomimage version*:
- Kotlin version*:
- Compose version(s)* (Jetpack/Multiplatform):
- JDK version(Only Desktop):

**Running Devices**

Please accurately describe the device Model, OS version, and CPU Architecture

- MacBookPro 14 2021; macOS 13.4.1; arm64
- XiaoMi MIX 4; MIUI 14.0.6; arm64

**Sample code**

If possible, provide a small piece of code that reproduces the problem. If the code snippet is too
large to paste here, please link to a Gist, a GitHub repo, or any other public code repository.

**Reproduction steps**

Please provide a detailed step-by-step guide on how to reproduce the issue you are experiencing.

**Expected behavior**

A clear and concise description of what 

you expected to happen.

**Screenshots**

**Additional context**

**Comment by yxiangTang** [comment]
![d63c1c146ae7a5d81392ee78c8075911(1)](https://github.com/user-attachments/assets/a620aea6-ea54-4572-91d4-735058b0f703)
就是这张图，使用Demo切换成GlideZoomImageView也是无法播放

**Comment by panpf** [comment]
别的 gif 图是否也不能播放？换成普通的 ImageView 再用 Glide 加载是否依然无法播放？

**Comment by yxiangTang** [comment]
> 别的 gif 图是否也不能播放？换成普通的 ImageView 再用 Glide 加载是否依然无法播放？

别的gif能播放，换成普通imageView用Glide加载也能正常播放

**Comment by 594happyboy** [comment]
兄嘚，应该就是 GlideImageSource 文件里 newGlideImageSource 方法中没有定义你加载的gif文件路径类型的问题，就是那个 model 参数。比如框架里面是没有绝对文件路径字符串这种类型的，所以你如果传入文件绝对路径的字符串时框架是加载不出来的，自己写一个分支条件就行了。
