### ISSUE TITLE
CoilZoomAsyncImage 点击事件响应有点慢，有没有合适的办法可以加快onTap的响应时间

### ISSUE THREAD

**Issue by lic2050** [panpf/zoomimage#47]
使用 CoilZoomAsyncImage显示大图 ，onTap响应时间有点慢，应该是为了双击事件，但是双击事件也想保留。有没有合适的办法可以加快onTap的响应时间

**Comment by panpf** [comment]
There is no room for optimization, that is, there is no delay control when the finger is lifted
