### ISSUE TITLE
Failed to transform zoomimage-view-1.0.0-beta04.aar (io.github.panpf.zoomimage:zoomimage-view:1.0.0-beta04)

### ISSUE THREAD

**Issue by MichaelRedo** [panpf/zoomimage#5]
先感谢下作者，我在单独引用这个`implementation("io.github.panpf.zoomimage:zoomimage-view:1.0.0-beta04")`
但是提示我下载不下来，我在阿里云镜像仓里也发现了这个依赖，但是Sync后一运行就会报
`Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform zoomimage-view-1.0.0-beta04.aar (io.github.panpf.zoomimage:zoomimage-view:1.0.0-beta04) to match attributes {artifactType=android-assets, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find zoomimage-view-1.0.0-beta04.aar (io.github.panpf.zoomimage:zoomimage-view:1.0.0-beta04).
        Searched in the following locations:
            https://maven.aliyun.com/repository/public/io/github/panpf/zoomimage/zoomimage-view/1.0.0-beta04/zoomimage-view-1.0.0-beta04.aar
            https://maven.aliyun.com/repository/public/io/github/panpf/zoomimage/zoomimage-view/1.0.0-beta04/zoomimage-view-1.0.0-beta04.jar`
我换成Glide的依赖也不行，劳烦作者大大帮忙看下，万分感谢！Salute to you！

**Comment by panpf** [comment]
https://maven.aliyun.com/repository/public/io/github/panpf/zoomimage/zoomimage-view/1.0.0-beta04/zoomimage-view-1.0.0-beta04.aar

**Comment by panpf** [comment]
https://maven.aliyun.com/repository/public/io/github/panpf/zoomimage/zoomimage-view/1.0.0-beta04/zoomimage-view-1.0.0-beta04.aar
https://repo1.maven.org/maven2/io/github/panpf/zoomimage/zoomimage-view/1.0.0-beta04/zoomimage-view-1.0.0-beta04.aar

**Comment by panpf** [comment]
https://maven.aliyun.com/repository/public/io/github/panpf/zoomimage/zoomimage-view/1.0.0-beta04/zoomimage-view-1.0.0-beta04.aar
https://repo1.maven.org/maven2/io/github/panpf/zoomimage/zoomimage-view/1.0.0-beta04/zoomimage-view-1.0.0-beta04.aar

上述两个链接，在浏览器里都可以访问下载，所以大概率还是你本机的网络问题，如果开了翻墙的话可以试试关闭翻墙
