### ISSUE TITLE
Keeping up dependencies up to date

### ISSUE THREAD

**Issue by FunkyMuse** [panpf/zoomimage#57]
As tech moves forward, it's a smart idea to introduce renovate or dependabot to keep some dependencies up to date, sometimes even minor versions have important fixes.

**Comment by panpf** [comment]
I don't think I need it. There are two situations when a dependent library is upgraded:
1. I don't need to modify the code, I just need to modify the version number. In this case, you can rely on the new version when using it
2. I need to modify the code to adapt to new destructive changes. In this case, I need to upgrade the version number and modify the code to adapt. In this case, dependabot is meaningless

This is just my current idea. Welcome to further communication
