### ISSUE TITLE
Feature container white space

### ISSUE THREAD

**Issue by maciek-s** [panpf/zoomimage#59]
Hi, really loved your work! I would like suggest a feature, similar to containerWhitespaceMultiple but with ability to pass px or dp to add white space at image top/right/bottom or left side.

**Comment by panpf** [comment]
It's okay, add the next version

**Comment by panpf** [comment]
Added in v1.1.0-rc02

**Comment by panpf** [comment]
https://github.com/panpf/zoomimage/blob/main/docs/wiki/offset.md#container-whitespace
