### ISSUE TITLE
zoomimage-compose-coil:1.0.0-beta04找不到ZoomState

### ISSUE THREAD

**Issue by XDao7** [panpf/zoomimage#6]
引入io.github.panpf.zoomimage:zoomimage-compose-coil:1.0.0-beta04后，编译找不到ZoomState类和rememberZoomState()方法。
之前引入io.github.panpf.zoomimage:zoomimage-compose-coil:1.0.0-beta03时是能正常调用ZoomState和rememberZoomState()的。

**Comment by panpf** [comment]
我查了 maven 库中的依赖配置没问题，各个子库也都有 beta04 版本。你打开 Project 面板下面的 External Libraries 看看有没有依赖成功，或者打开 Build 面板看看 sync 是否成功，大概率是你网络问题导致下载依赖失败了，

**Comment by XDao7** [comment]
![Dingtalk_20231101113250](https://github.com/panpf/zoomimage/assets/50022005/20d52c42-c873-4189-a22c-c633ec0a4389)

**Comment by panpf** [comment]
你的这个是不对的，beta04 版本开始支持 compose multiplatform 了，所以这里你看到的应该是 zoomimage-core-android 和 zoomimage-compose-android，我猜应该是你用的 android 插件版本太低了，不支持 compose multiplatform，你往上升一下试试

**Comment by XDao7** [comment]
感谢，我尝试一下

**Comment by XDao7** [comment]
老哥，我升级了一下AS，目前是Android Studio Giraffe | 2022.3.1 Patch 2，AGP版本是8.1.2，Gradle是8.0，kotlinCompilerExtensionVersion是1.4.3，org.jetbrains.kotlin.android是1.8.10。
引入io.github.panpf.zoomimage:zoomimage-compose-coil:1.0.0-beta04还是和上面那个图一样的结果。
请问我还需要升级哪个版本？或者是需要安装其他的插件才能支持compose multiplatform？

**Comment by panpf** [comment]
1. 我只能给你我的其它项目的版本列表作参考：
 * kotlin 1.9.10
 * android plugin 8.1.1
 * gradle 8.1.1
 * compose 1.5.1
 * compose compiler 1.5.3
2. 不需要其它插件，正常使用即可，例如你配置依赖的时候写的是 zoomimage-compose，但最终 gradle 或者 android 插件（我也不知道他俩到底是谁）会根据自身的平台（android 或桌面）再去引用具体平台的包，android 上最终会依赖 zoomimage-compose-android

正确依赖的话应该是下图的样子
![image](https://github.com/panpf/zoomimage/assets/3250512/58aa7a60-afc5-4e76-b8b0-805479739261)

**Comment by XDao7** [comment]
我知道为啥了，不是版本的问题。
我项目中用了aliyun镜像，那个不支持compose multiplatform，注释掉镜像之后就OK了。
(╬▔皿▔)凸
