### ISSUE TITLE
双指缩放图片跳闪

### ISSUE THREAD

**Issue by 594happyboy** [panpf/zoomimage#62]
安卓平台，OPPO。

使用最新 v1.1.0-rc01 的 oomimage-sample-release-1.1.0-rc01.apk 包复现。

只测试了 View 中的组件：
Sketch、Coil、Glide、Basic
均有下述问题

复现步骤：
1.双指触摸。在下方视频中都是上侧的手指先触摸，然后下侧手指再触摸。
2.双指放大。在下方视频中都是上侧的手指先抬起，然后下侧手指再抬起。

造成结果：
在初始状态下进行上述步骤放大时，能够正常放大，但是当图片达到一定大小时继续进行上述步骤放大，
上侧手指放开后（此时下侧手指仍未抬起），图片将会跳闪平移。如视频后面几次放大所示。

视频如下：

https://github.com/user-attachments/assets/e105c43c-eb28-4d71-a6cb-4dbb3e50a348

**Comment by panpf** [comment]
我按你说的测试并没有复现问题，我是正在缩放大最大以后，松手时先松先按下的手指。测试手机是小米的，你能否再提供更详细的复现方法？

**Comment by 594happyboy** [comment]
您的复现方法是对的。
我刚才又测试了几部华为、小米手机，确实正常。
也只有刚才出问题的那个oppo（oppo k7x）手机能稳定复现这个问题，可能是它系统魔改？

**Comment by panpf** [comment]
有可能 oppo 改了事件分发的逻辑了。我这里目前没有 oppo 的设备，你要是有空的话可以试着改一下
