### ISSUE TITLE
采用Glide图片加载框架的放大组件在阿拉伯语言情况下会有bug

### ISSUE THREAD

**Issue by fanyafeng** [panpf/zoomimage#65]
![20241203-111403](https://github.com/user-attachments/assets/afbe4e73-6a52-4946-975b-a072f7793077)
![20241203-111407](https://github.com/user-attachments/assets/c99c6162-c134-4da0-a206-fed4d52ec17d)
第一个shi是正常情况下，第二个是阿拉伯语言情况下，图片会有偏移

**Comment by panpf** [comment]
未复现，请提供完整测试用例以及测试环境说明

**Comment by panpf** [comment]
牛用的具体是哪个组件？另外阿拉伯语言用的是哪个，我看不懂语言选项里的阿拉伯，不知道你选的是哪个，请在模拟器上测试

**Comment by fanyafeng** [comment]
查看大图组件：api("io.github.panpf.zoomimage:zoomimage-compose-glide:1.1.0-rc01")
图片组件：implementation("com.github.bumptech.glide:compose:1.0.0-beta01")

国家：Arabic
![20241203-152744](https://github.com/user-attachments/assets/ce1c4154-0893-4458-ad9d-039c250b71e5)

**Comment by panpf** [comment]
已经在 dev 分支上修复了此问题，并且 alignment 属性也支持了 RTL，正在发布快照版本，两个小时后你可以从快照仓库中下载 1.1.0-rc03-SNAPSHOT 版本测试一下还有没有问题

**Comment by fanyafeng** [comment]
> 已经在 dev 分支上修复了此问题，并且 alignment 属性也支持了 RTL，正在发布快照版本，两个小时后你可以从快照仓库中下载 1.1.0-rc03-SNAPSHOT 版本测试一下还有没有问题

老哥迅速啊，厉害

**Comment by panpf** [comment]
试了吗 兄弟？

**Comment by panpf** [comment]
顺带试试 RTL 模式下 alignment 属性

**Comment by fanyafeng** [comment]
> 试了吗 兄弟？

昨天拉代码没拉下来，今天再试试

**Comment by fanyafeng** [comment]
> 不用拉代码，只用配一下快照仓库，然后版本改为 1.1.0-rc03-SNAPSHOT 即可

api("io.github.panpf.zoomimage:zoomimage-compose-glide:1.1.0-rc03-SNAPSHOT") 是这个地址吧，这个库没有拉下来，刚试了下还不行

**Comment by panpf** [comment]
你要先配置快照仓库

**Comment by fanyafeng** [comment]
> 试了吗 兄弟？

图片可以了， RTL 模式下 alignment 属性没试，没有场景

**Comment by panpf** [comment]
c
