### ISSUE TITLE
旋转为什么要固定90度的倍数，不能根据手势旋转任意角度吗

### ISSUE THREAD

**Issue by sunlimiter** [panpf/zoomimage#68]
rotate() targetRotation

**Comment by panpf** [comment]
因为省事儿😄

**Comment by sunlimiter** [comment]
😭好吧，如果要任意角度旋转就只能外面再套一层了

**Comment by panpf** [comment]
1. 任意角度旋转只存在于手势旋转的过程中，松手以后还是要调整到 90 的倍数的，所以 rotate() 方法没必要支持任意角度
2. 至于手势旋转个人感觉使用体验并不好，不如按钮点击舒服，也会跟双指缩放有些冲突，头部 App 如微信、微博、哔哩哔哩等都没有支持手势旋转，所以我也就没做这个

**Comment by sunlimiter** [comment]
🫡了解

**Comment by lazycat-k1** [comment]
> 1. 任意角度旋转只存在于手势旋转的过程中，松手以后还是要调整到 90 的倍数的，所以 rotate() 方法没必要支持任意角度
> 2. 至于手势旋转个人感觉使用体验并不好，不如按钮点击舒服，也会跟双指缩放有些冲突，头部 App 如微信、微博、哔哩哔哩等都没有支持手势旋转，所以我也就没做这个

明明一个旋转按钮就能完成， 非要双指旋转， 真不知道这些相册应用是怎么想的。?
