### ISSUE TITLE
单指缩放问题

### ISSUE THREAD

**Issue by 1045290202** [panpf/zoomimage#7]
单指缩放好像有点问题
无法通过zoomable.disabledGestureTypeState.value = GestureType.ONE_FINGER_SCALE关闭单指缩放，且单指缩放与setOnLongClickListener冲突，会同时触发。还有一个问题是单指缩放会先触发双击缩放，单指缩放的变换位置变成了右下角

Select one of the platforms below:

- Android

**Versions**

- zoomimage version*:1.0.0-beta06
- Kotlin version*:1.9.0
- Compose version(s)* (Jetpack/Multiplatform):无
- Running Devices (*) (Model, OS, CPU Architecture, JDK.):
  - XiaoMi 13 Pro; MIUI 14.0.23.9.18.DEV; arm64

```
this.imageView.zoomable.disabledGestureTypeState.value = GestureType.ONE_FINGER_SCALE
this.imageView.setOnLongClickListener {
    App.output.showImageLongClickDialog(this.imageInfo!!.path)

    return@setOnLongClickListener true
}
this.imageView.setOnClickListener {
    (this.itemView.context as ImageActivity).onBackPressedDispatcher.onBackPressed()
}
```

**Reproduction steps**

无法通过zoomable.disabledGestureTypeState.value = GestureType.ONE_FINGER_SCALE关闭单指缩放，且单指缩放与setOnLongClickListener冲突，会同时触发。还有一个问题是单指缩放会先触发双击缩放，单指缩放的变换位置变成了右下角

**Comment by panpf** [comment]
问题 1：没有复现，请提供完整复现代码
问题 2：下个版本不会再同时触发
问题 3：无法复现，请提供复现步骤或演示视频或动图

**Comment by 1045290202** [comment]
- 问题一：我是这样禁用单指手势的`imageView.zoomable.disabledGestureTypeState.value = GestureType.ONE_FINGER_SCALE`，如果设置成`GestureType.ONE_FINGER_SCALE or GestureType.TWO_FINGER_SCALE`则不会触发单指和双指手势，但如果设置成`GestureType.ONE_FINGER_SCALE or GestureType.DOUBLE_TAP_SCALE`依然会触发单指；
- 问题三：可以参考下面的视频，全程是单指，快速双击按住拖动以后会先触发双击放大，然后再触发单指手势，且还会移动图片的位置；

https://github.com/panpf/zoomimage/assets/32164924/67eb089e-6876-4586-8d81-96e0d03ce646

相关代码在https://github.com/1045290202/DeleteRecentPictures/blob/master/app/src/main/java/com/sjk/deleterecentpictures/activity/image/ImageActivityViewPagerAdapter.kt#L81
如果方便的话可以下载我的app试试https://github.com/1045290202/DeleteRecentPictures/releases/latest

**Comment by panpf** [comment]
问题 3：这是由于 View 版本的手势识别有 bug，双击和手势缩放同时触发了导致的。已修复，预计周五发下个版本，着急的话可以先发个 SNAPSHOT 版本
问题 1：这个问题不存在，因为你压根没有开启单指缩放功能，开启的方法请查看文档（https://github.com/panpf/zoomimage/blob/main/docs/wiki/scale_zh.md#%E5%8D%95%E6%8C%87%E7%BC%A9%E6%94%BE）。之所以让你误以为开启了是因为问题 3 导致的

**Comment by 1045290202** [comment]
> 问题 3：这是由于 View 版本的手势识别有 bug，双击和手势缩放同时触发了导致的。已修复，预计周五发下个版本，着急的话可以先发个 SNAPSHOT 版本 问题 1：这个问题不存在，因为你压根没有开启单指缩放功能，开启的方法请查看文档（ https://github.com/panpf/zoomimage/blob/main/docs/wiki/scale_zh.md#%E5%8D%95%E6%8C%87%E7%BC%A9%E6%94%BE ）。之所以让你误以为开启了是因为问题 3 导致的

抱歉，是我理解错了单指缩放的意思，需要长按才能触发。其他库的单指缩放貌似是双击并按住拖动触发的

**Comment by panpf** [comment]
单指双击并按住拖动缩放也不是不行，有哪些库是这么做的呢？

**Comment by 1045290202** [comment]
> 单指双击并按住拖动缩放也不是不行，有哪些库是这么做的呢？

https://github.com/davemorrissey/subsampling-scale-image-view 我记得这个库好像是单指双击并按住拖动缩放的，其他比如系统相册、QQ、最右、知乎、美团都是这样的

**Comment by panpf** [comment]
1.0.0-beta07 版本已发布，此问题已修复，单指缩放手势改为了通用的双击按住屏幕然后上下滑动

**Comment by 1045290202** [comment]
> 1.0.0-beta07 版本已发布，此问题已修复，单指缩放手势改为了通用的双击按住屏幕然后上下滑动

好的我试试，谢谢大佬

**Comment by panpf** [comment]
问题解决了吗？

**Comment by 1045290202** [comment]
> 问题解决了吗？

已经解决了，暂时没有遇到手势上的问题了

**Comment by panpf** [comment]
好的，有问题及时反馈啊

**Comment by 1045290202** [comment]
> 好的，有问题及时反馈啊

好的👌
