### ISSUE TITLE
如何获取手势缩放的倍数？

### ISSUE THREAD

**Issue by lic2050** [panpf/zoomimage#8]
在Compose HorizontalPager中使用CoilZoomAsyncImage, 当图片双指放大，滑动图片到边缘后，滑动手势会与Pager的滑动有一些冲突，我想在当用户放大图片后，禁用HorizontalPager的滑动。此时需要获取到图片的手势缩放倍数是否为1。

zoomState.zoomable.transform.scale.scaleX返回的是图像内容的缩放倍数而不是手势缩放倍数，当图片小100*100，控件大小为200*200时，缩放模式为Fit，此时默认状态下scaleX是2。我需要的是此时默认scaleX大小为1，这个手势缩放的倍数该怎么算

**Comment by panpf** [comment]
你的需求是只有在默认缩放倍数时才允许 Pager 滑动，只要用户操作产生了缩放就不让 Pager 滑动？
如果是这样的话你可以看看 zoomState.zoomable.userTransform.scaleX 属性，只要它不为 1f 就说明用户操作产生了缩放

**Comment by lic2050** [comment]
滑动到边缘继续滑动会触发 Pager 的滑动这个没问题，是滑动不松手，然后再往回滑，此时会出问题，事件看这像是被截断了。
zoomState.zoomable.userTransform可以满足需求。不过我刚刚在测试的时候发现在双指缩小，然后松开，缩放自动回到1的时候，有很小概率动画结束但是scale不为1的情况，停留在0.99931854，还有1.0000001

**Comment by panpf** [comment]
> 滑动到边缘继续滑动会触发 Pager 的滑动这个没问题，是滑动不松手，然后再往回滑，此时会出问题，事件看这像是被截断了

没明白是什么问题，能否描述的详细点

scale 不为 1f 是正常情况，浮点数计算结果总是不那么精确，比较的时候一般都要格式化一下只保留一位或两位小数再比较

**Comment by lic2050** [comment]
https://github.com/panpf/zoomimage/assets/24469361/0b62671f-ddb1-4a9b-b42b-daca67b66dba
视频第5秒，我只往右回滑了一点点距离，但是整个Pager自动归位了

图片放大后，先向左滑，当滑动到一半的时候，不松手，再向右往回滑，此时Pager会像手势松开了一样直接归为。

**Comment by panpf** [comment]
1.0.0-beta07 版本已发布，已修复此问题

**Comment by panpf** [comment]
麻烦兄弟验证一下 beta07 版本修复的结果是否有效

**Comment by lic2050** [comment]
好了，没问题了
