### ISSUE TITLE
希望zoomimage-view-glide的newGlideImageSource可以增加对GlideUrl类型的model的支持

### ISSUE THREAD

**Issue by pzllla** [panpf/zoomimage#9]
在使用zoomimage-view-glide 1.0.0-beta10加载图片的时候，使用了glide内置GlideUrl类型的model (com.bumptech.glide.load.model.GlideUrl) 以支持指定header
```java
Glide.with(context)
         .load(GlideUrl(url, headers))
         .into(itemImage)
```

运行时发现一个warning
<img width="632" alt="image" src="https://github.com/panpf/zoomimage/assets/131447030/f98a7358-e1a0-424c-be2b-6c35c0014964">
看了下代码，发现newGlideImageSource只支持简单的String Int等类型的model，
<img width="1014" alt="image" src="https://github.com/panpf/zoomimage/assets/131447030/a9d653a3-d84c-4d37-97ac-323ad4e0cef7">
希望增加对GlideUrl类型的model的支持

**Comment by panpf** [comment]
1.0.0 支持 GlideUrl 了
